### ISSUE TITLE
commit-msg is not a good prefix

### ISSUE THREAD

**Issue by tumashu** [kidd/git-msg-prefix#2]
I do not think commit-msg is a good prefix, it seem to prefix: "commit-"

**Comment by kidd** [comment]
Hello!
So, the whole package would be named commit-prefix? I'm totally open to it change the name to something clearer.

**Comment by tumashu** [comment]
icommit :-)

**Comment by tumashu** [comment]
commitext

**Comment by tumashu** [comment]
commitxt

**Comment by tumashu** [comment]
fastcommit

**Comment by tumashu** [comment]
Naming is a hard thing :-(

**Comment by kidd** [comment]
naming-is-a-hard-thing.el 

I like it! :)

**Comment by tumashu** [comment]
maybe you can rename it to counsel-vcsmsg and pull request it to counsel package :-)

**Comment by kidd** [comment]
it ended up being git-msg-prefix.
