### ISSUE TITLE
pick commit: how can I make candidate sort by commit time

### ISSUE THREAD

**Issue by linchen2chris** [kidd/git-msg-prefix#9]
![image](https://user-images.githubusercontent.com/3970087/67845641-c8f9cd80-fb3a-11e9-9e58-2b789dc90cd1.png)
now the candidate git message list is sorted by alphibetally, How can I make it sort by the commit time

**Comment by linchen2chris** [comment]
find something here https://emacs.stackexchange.com/questions/41801/how-to-stop-completing-read-ivy-completing-read-from-sorting
so the problem is completing-read will auto sort, I just need to stop it sorting

**Comment by kidd** [comment]
Hey, thanks for creating the issue. It seems like an easy fix. Please try the branch on #10 and we can merge it afterwards.

**Comment by linchen2chris** [comment]
@kidd  Thanks, https://github.com/kidd/git-msg-prefix.el/pull/10 can fix it.
